name: flutter_rain_effect
description: A customizable package for adding rain and splash effects to Flutter apps. Supports multiple platforms with adjustable rain intensity, color, size, and even text-based raindrops.

version: 1.0.0
homepage: https://github.com/YoRuHub/flutter_rain_effect

environment:
  sdk: ^3.6.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_rain_effect
        pluginClass: FlutterRainEffectPlugin
      ios:
        pluginClass: FlutterRainEffectPlugin
      macos:
        pluginClass: FlutterRainEffectPlugin
      linux:
        pluginClass: FlutterRainEffectPlugin
      windows:
        pluginClass: FlutterRainEffectPluginCApi
